print("**********************")
print("*                                                            *")
print("* Bienvenido a la Calculadora de Alexis Moreno        *")
print("*                                                            *")
print("* La suma de sus operaciones es:                             *")
print("* Suma=                                                      *")              
print("* Resta=20                                                   *")
print("* Multiplicacion=30                                          *")
print("* Division=40                                                *")
print("* Este programa fue realizado por Alexis Moreno        *")
print("**********************")